# treefmt.toml for qrxnz's dotfiles

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.shell]
command = "shfmt"
options = [
  "-i",
  "2",
  "-s",
  "-w",
]
includes = [
  "*.sh",
  "files/hypr/scripts/*",
  "files/zshrc/zshrc",
]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = [
  "*.css",
  "*.json",
  "*.jsonc",
  "*.yaml",
  "*.yml",
  "*.md",
]

[formatter.toml]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
