## name: Rosé Pine
## author: mvllow
## license: MIT
## upstream: https://github.com/rose-pine/kitty/blob/main/dist/rose-pine.conf
## blurb: All natural pine, faux fur and a bit of soho vibes for the classy minimalist

foreground               #e0def4
background               #191724
selection_foreground     #e0def4
selection_background     #403d52

cursor                   #524f67
cursor_text_color        #e0def4

url_color                #c4a7e7

active_tab_foreground    #e0def4
active_tab_background    #26233a
inactive_tab_foreground  #6e6a86
inactive_tab_background  #191724

active_border_color      #31748f
inactive_border_color    #403d52

# black
color0   #26233a
color8   #6e6a86

# red
color1   #eb6f92
color9   #eb6f92

# green
color2   #31748f
color10  #31748f

# yellow
color3   #f6c177
color11  #f6c177

# blue
color4   #9ccfd8
color12  #9ccfd8

# magenta
color5   #c4a7e7
color13  #c4a7e7

# cyan
color6   #ebbcba
color14  #ebbcba

# white
color7   #e0def4
color15  #e0def4

# Font
font_family      ComicMono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0

# Opacity
background_opacity 0.9

# Bar
tab_bar_edge top

# Bindings
map kitty_mod+enter new_window_with_cwd
map ctrl+shift+e next_layout

# Vim bindings

# Scrolling
map kitty_mod+k scroll_line_up
map kitty_mod+j scroll_line_down
map kitty_mod+b scroll_page_up
map kitty_mod+f scroll_page_down
map kitty_mod+g scroll_home
map kitty_mod+shift+g scroll_end

# Move between prompts
map kitty_mod+up scroll_to_prompt -1
map kitty_mod+down scroll_to_prompt 1

# Copy/Paste
map kitty_mod+y copy_to_clipboard
map kitty_mod+p paste_from_clipboard

# Switch between windows
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down

# Switch between tabs
map option+tab next_tab
map option+shift+tab previous_tab
