# .------..------..------..------..------.
# |Z.--. ||S.--. ||H.--. ||R.--. ||C.--. |
# | :(): || :/\: || :/\: || :(): || :/\: |
# | ()() || :\/: || (__) || ()() || :\/: |
# | '--'Z|| '--'S|| '--'H|| '--'R|| '--'C|
# `------'`------'`------'`------'`------'


#
# Paths & variables
#

# tools
export PATH="$PATH:$HOME/.local/bin/"

# cargo
export PATH="$PATH:$HOME/.cargo/bin/"

# go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# terminal
export TERM=xterm-256color

# nix config
export NIX_CONF_DIR=$HOME/.config/nix

# colima
export DOCKER_HOST="unix://$HOME/.colima/default/docker.sock"

#
# Homebrew
#

# init homebrew
if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

#
# Nix
#

# nix things
if [ -e ~/.nix-profile/etc/profile.d/nix.sh ]; then . ~/.nix-profile/etc/profile.d/nix.sh; fi

if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

# Launch Nushell if interactive and not disabled by NO_NU
if [[ -o interactive ]] && [[ -z "$NO_NU" ]] && command -v nu >/dev/null 2>&1; then
    exec nu --config "$HOME/.config/nushell/config.nu" --env-config "$HOME/.config/nushell/env.nu"
fi
