#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(waybar mako syncthing weektodo)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Wallpaper (swaybg)
exec= swaybg --image ~/.dotfiles/wallpapers/catppuccin/blossom.png --mode fill &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

# Remmina
remmina --icon &

# Syncthing
syncthing -no-browser &

# Lunatask
lunatask
