[General]
  Backend = "gist"
  Cmd = []
  Color = false
  Column = 40
  Editor = "vim"
  Format = "[$description]: $command $tags"
  SelectCmd = "fzf --ansi --layout=reverse --border --height=90% --pointer=* --cycle --prompt=Snippets:"
  SnippetDirs = []
  SnippetFile = "/Users/qrxnz/.config/pet/snippet.toml"
  SortBy = ""
